### PR TITLE
Follow up bug 912121, fix editor broken

### PR DESCRIPTION
**Pull request by yfdyh000**
I'm not sure it is perfect, but looks fine.

https://bugzilla.mozilla.org/show_bug.cgi?id=912121

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Doesn't `require` raise an exception if the file isn't there?

**Comment by yfdyh000** [comment]
You're right, I missed it despite repeated tests. Fixed, although it seems not nice, I hope this correctly.

**Comment by JasonBarnabe** [comment]
Can you include some comments on why this is done? For example `// For Firefox xx to xx`

**Comment by yfdyh000** [comment]
Comments have been added to js, ​​not for xul. Sorry for the delay.

**Comment by yfdyh000** [comment]
@JasonBarnabe Can you publish it to AMO?

**Pull request merged**
